services:
  app:
    build:
      context: ../app
    container_name: pollution-app
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - KIE_BASE_URL=http://jbpm:8080/kie-server/services/rest
      - KIE_CONTAINER_ID=pollution-rules_1.0.0
      - KIE_USER=kieserver
      - KIE_PASS=kieserver1!
      - KIE_GROUP_ID=com.myspace.pollution
      - KIE_ARTIFACT_ID=pollution-rules
      - KIE_VERSION=1.0.0
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=qwen2.5-coder:3b
    depends_on:
      - jbpm
    volumes:
      - ../app/data:/usr/src/app/data

  jbpm:
    image: jboss/jbpm-server-full:latest
    container_name: jbpm-server-full
    ports:
      - "8080:8080"
      - "8001:8001"
    volumes:
      - ../runtime/niogit:/opt/jboss/wildfly/bin/.niogit
  ollama:
    image: ollama/ollama:latest
    container_name: pollution-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
  grafana:
    image: grafana/grafana:latest
    container_name: pollution-grafana
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana-data:/var/lib/grafana
      - ../app/data:/app/data
    depends_on:
      - app

volumes:
  grafana-data:
  ollama-data: